version: '3'

services:
  social_media_db:
    image: mongo:5
    container_name: social_media
    restart: always
    ports:
      - 27020:27017
    environment:
      MONGODB_DATABASE: SocialMedia
    volumes:
      - ./db/mongodb:/data/db

  management_user_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: management_user
    restart: always
    user: root
    expose:
      - 1433
    ports:
      - "1435:1433"
    environment:
      MSSQL_SA_PASSWORD: "mysecret1234!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
       - ./db/mssqldb:/var/opt/mssql